export const products = [
    [
        {id: '1', title: 'Super Cool T-Shirt', price: 49.99},
        {id: '2', title: 'Black T-Shirt', price: 19.99},
        {id: '3', title: 'Red T-Shirt', price: 19.99},
        {id: '4', title: 'Green T-Shirt', price: 19.99},
        {id: '5', title: 'Blue T-Shirt', price: 19.99},
        {id: '6', title: 'White T-Shirt', price: 19.99},
    ],
    [
        {id: '7', title: 'Super Cool Jacket', price: 199.99},
        {id: '8', title: 'Black Jacket', price: 79.99},
        {id: '9', title: 'Red Jacket', price: 79.99},
        {id: '10', title: 'Green Jacket', price: 79.99},
        {id: '11', title: 'Blue Jacket', price: 79.99},
        {id: '12', title: 'White Jacket', price: 79.99},
    ],
    [
        {id: '13', title: 'Super Cool Coat', price: 199.99},
        {id: '14', title: 'Black Coat', price: 129.99},
        {id: '15', title: 'Red Coat', price: 129.99},
        {id: '16', title: 'Green Coat', price: 129.99},
        {id: '17', title: 'Blue Coat', price: 129.99},
        {id: '18', title: 'White Coat', price: 129.99},
    ],
    [
        {id: '19', title: 'Super Cool Sweatshirt', price: 159.99},
        {id: '20', title: 'Black Sweatshirt', price: 49.99},
        {id: '21', title: 'Red Sweatshirt', price: 49.99},
        {id: '22', title: 'Green Sweatshirt', price: 49.99},
        {id: '23', title: 'Blue Sweatshirt', price: 49.99},
        {id: '24', title: 'White Sweatshirt', price: 49.99},
    ],
    [
        {id: '25', title: 'Super Cool Hoodie', price: 99.99},
        {id: '26', title: 'Black Hoodie', price: 49.99},
        {id: '27', title: 'Red Hoodie', price: 49.99},
        {id: '28', title: 'Green Hoodie', price: 49.99},
        {id: '29', title: 'Blue Hoodie', price: 49.99},
        {id: '30', title: 'White Hoodie', price: 49.99},
    ],
    [
        {id: '31', title: 'Super Cool Jeans', price: 99.99},
        {id: '32', title: 'Black Jeans', price: 49.99},
        {id: '33', title: 'Red Jeans', price: 49.99},
        {id: '34', title: 'Green Jeans', price: 49.99},
        {id: '35', title: 'Blue Jeans', price: 49.99},
        {id: '36', title: 'White Jeans', price: 49.99},
    ],
    [
        {id: '37', title: 'Super Cool Pants', price: 99.99},
        {id: '38', title: 'Black Pants', price: 49.99},
        {id: '39', title: 'Red Pants', price: 49.99},
        {id: '40', title: 'Green Pants', price: 49.99},
        {id: '41', title: 'Blue Pants', price: 49.99},
        {id: '42', title: 'White Pants', price: 49.99},
    ],
    [
        {id: '43', title: 'Super Cool Shorts', price: 49.99},
        {id: '44', title: 'Black Shorts', price: 29.99},
        {id: '45', title: 'Red Shorts', price: 29.99},
        {id: '46', title: 'Green Shorts', price: 29.99},
        {id: '47', title: 'Blue Shorts', price: 29.99},
        {id: '48', title: 'White Shorts', price: 29.99},
    ],
]